font_family Hack
bold_font auto
italic_font auto
font_size 14.0

background #1a1b24
background_opacity 0.80

foreground #ffffff
selection_background #6dd7e7
selection_foreground #191927

#cursor #f5e0dc

color0  #222235
color1  #08d6f1
color2  #19beb9
color3  #2a2f3d
color4  #60f5ff
color5  #c7eafc
color6  #e3f8ff
color7  #ffffff
color8  #555564
color9  #71def6
color10 #7feede
color11 #92fde6
color12 #b7fdfa
color13 #b7dfed
color14 #e3f8ff
color15 #ffffff

wayland_titlebar_edge_rounding 14

hide_window_decorations yes

scrollbar_hide yes