listener {
    timeout = 600
    on-timeout = hyprlock
    #on-timeout = hyprctl dispatch dpms off                            # screen off when timeout has passed
    #on-resume = hyprctl dispatch dpms on && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}