source = ~/.config/hypr/conf.d/00-autostart.conf
source = ~/.config/hypr/conf.d/00-workspaces.conf
source = ~/.config/hypr/conf.d/10-monitors-active.conf
source = ~/.config/hypr/conf.d/20-windows.conf
source = ~/.config/hypr/conf.d/30-keybinds.conf
source = ~/.config/hypr/conf.d/40-style.conf


input {
  numlock_by_default= true
  kb_layout = us,sv
}

misc {
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}