source = ~/.config/hypr/conf.d/00-workspaces.conf
source = ~/.config/hypr/conf.d/10-monitors-active.conf
source = ~/.config/hypr/conf.d/20-windows.conf
source = ~/.config/hypr/conf.d/30-keybinds.conf
source = ~/.config/hypr/conf.d/40-style.conf

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = waybar
exec-once = hypridle
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = nm-applet --indicator
exec-once = pkill swww-daemon; swww-daemon --format xrgb
exec-once = swww img ~/Pictures/Wallpapers/wall.jpg --transition-type any --transition-duration 1
# Clipboard history (cliphist)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = udiskie
exec-once = xembedsniproxy
exec-once = swaync
exec-once = ~/.config/hypr/scripts/media-watcher.sh &

input {
  numlock_by_default= true
  kb_layout = us,sv
}

misc {
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}