animations {
  enabled = true
  bezier = ios, 0.20, 0.85, 0.20, 1.0

  animation = windows, 1, 2, ios
  animation = windowsIn, 1, 1, ios
  animation = workspaces, 1, 2, ios

  animation = fade, 1, 1, default

  animation = border, 1, 2, ios
}