exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = waybar
exec-once = hypridle

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = nm-applet --indicator

exec-once = quickshell -p ~/.config/skwd-wall/daemon.qml
# Clipboard history (cliphist)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = udiskie
exec-once = xembedsniproxy
exec-once = swaync

exec-once = [workspace 2 silent] webstorm
exec-once = [workspace 4 silent] steam
exec-once = [workspace 4 silent] gtk-launch battlenet
exec-once = [workspace 5 silent] discord
exec-once = [workspace 5 silent] google-chrome-stable
exec-once = [workspace 6 silent] spotify
exec-once = [workspace 7 silent] betterbird
