monitorv2 {
  output = DP-4
  mode = highres@highrr
  position = 0x0
  scale = 1
  bitdepth = 10
  cm = hdr

  sdrbrightness = 1.10
  sdrsaturation = 1.10
}

monitorv2 {
  output = DP-5
  mode = highres@highrr
  position = 3840x0
  scale = 1
  bitdepth = 8
}

monitor = ,preferred,auto,auto