windowrule {
 name = media-tag-opaque
 opaque = on
 match:tag = media
}

windowrule {
 name = volume-control
 float = on
 match:class = hyprmixer
 size = 768 500
 move = (cursor_x-(window_x/2)) (cursor_y+30)
}

windowrule {
 name = hide-faugus
 workspace = special:faugus silent
 match:class = faugus-launcer
}

#windowrule {
 #name = steam
 #float = on
 #center = on
 #match:class = (steam|steam_app_0)
 #match:class = steam
#}

windowrule {
 name = battle-net
 float = on
 size = 1564 879
 move = (cursor_x-(window_x/2)) (cursor_y-(window_y/2))
 match:class = (steam_app_0)
 match:title = ^Battle.net$
}

windowrule {
 name = wow-up
 float = on
 size = 1450 1135
 #move = 2270 110
 move = (cursor_x-(window_x/2)) (cursor_y-(window_y/2))
 match:class = (WowUp)
 match:title = ^WowUp.io$
}

windowrule {
 name = silent-on-secondary
 workspace = 2 silent
 match:class = (discord)
}

windowrule {
 name = silent-on-secondary-2
 workspace = 4 silent
 match:class = (spotify)
}

windowrule {
  name = save-dialog-4k
  float = on
  match:workspace = m[0]
  match:class = (google-chrome)
  match:title = ^Save File$
  size = 854 480
  move = (cursor_x-(window_x/2)) (cursor_y-(window_y/2))
}

windowrule {
  name = save-dialog-1440
  float = on
  match:workspace = m[1]
  match:class = (google-chrome)
  match:title = ^Save File$
  size = 854 480
  move = (cursor_x-(window_x/2)-1920) (cursor_y-(window_y/2))
}

#windowrule {
#  name = jetbrains-popup-focus
#  stay_focused = on
#  match:class = ^jetbrains-webstorm$
#  match:title = ^win[0-9]+$
#}

#windowrule {
#  name = wofi-keep-focus
#  stay_focused = on
#  match:class = ^(wofi)$
#}
