windowrule {
 name = video-rules
 idle_inhibit = on
 opaque = on
 match:tag = media
}

windowrule {
 name = silent-on-main
 workspace = 1 silent
 float = on
 center = on
 match:class = (steam|faugus-launcer|steam_app_0)
}

windowrule {
 name = battle-net
 float = on
 center = on
 size = 1564 879
 match:class = (steam_app_0)
 match:title = ^Battle.net$
}

windowrule {
 name = wow-up
 float = on
 size = 1450 1135
 move = 2270 110
 match:class = (WowUp)
 match:title = ^WowUp.io$
}

windowrule {
 name = silent-on-secondary
 workspace = 2 silent
 match:class = (discord)
}

windowrule {
 name = silent-on-secondary-2
 workspace = 4 silent
 match:class = (spotify)
}

windowrule {
 name = wow-on-3
 workspace = 3
 fullscreen = on
 match:class = ^steam_app_0$
 match:title = ^World of Warcraft$
}

windowrule {
 name = save-dialog
 float = on
 match:class = (google-chrome)
 match:title = ^Save File$
}

#windowrule {
#  name = jetbrains-popup-focus
#  stay_focused = on
#  match:class = ^jetbrains-webstorm$
#  match:title = ^win[0-9]+$
#}

#windowrule {
#  name = wofi-keep-focus
#  stay_focused = on
#  match:class = ^(wofi)$
#}
