windowrule {
 name = volume-control
 float = on
 match:class = hyprmixer
 size = 768 500
 move = (cursor_x-(window_x/2)) (cursor_y+30)
}

windowrule {
 name = hide-faugus
 workspace = special:faugus silent
 match:class = faugus-launcer
}

windowrule {
 name = discord
 workspace = 5 silent
 match:class = discord
}

#windowrule {
 #name = steam
 #float = on
 #center = on
 #match:class = (steam|steam_app_0)
 #match:class = steam
#}

windowrule {
  name = file-dialog
  float = on
  match:title = ^((Save|Open) File(s|)|Select a folder this site can view)$
  center = on
  size = 1080 720
}

windowrule {
  name = betterbird-popup
  float = on
  match:class = (eu.betterbird.Betterbird)
  match:initial_title = ^$
  center = on
  size = 1080 720
}

windowrule {
  name = easy-effects
  float = on
  match:class = com.github.wwmm.easyeffects
  center = on
  size = 1080 720
}



#windowrule {
#  name = wofi-keep-focus
#  stay_focused = on
#  match:class = ^(wofi)$
#}
