general {
  gaps_in = 8
  gaps_out = 12
  border_size = 1
  layout = dwindle
  resize_on_border = true

  col.active_border = rgba(1f6f7acc)
  #col.inactive_border = rgba(ffffff12)

}

decoration {
  rounding = 4

  active_opacity = 1
  inactive_opacity = 0.75

  shadow {
    enabled = true
    range = 20
    render_power = 4
    color = rgba(00000055)
  }

  blur {
    enabled = true
    size = 8
    passes = 3
    new_optimizations = true
  }
}

animations {
  enabled = true
  bezier = ios, 0.20, 0.85, 0.20, 1.0

  animation = windows, 1, 2, ios
  animation = windowsIn, 1, 1, ios
  animation = workspaces, 1, 2, ios

  animation = fade, 1, 1, default

  animation = border, 1, 2, ios
}

dwindle {
  pseudotile = true
  preserve_split = true
}